/* Greenfield Academy — interactive demo (live, role-aware) */

// ════════════════════════════ DATA ════════════════════════════
const seedStudents = [
  { name: 'Ava Mensah',      cls: 'JSS 2', guardian: 'Kofi Mensah',    att: 98, fee: 320, status: 'Paid',    method: 'Card' },
  { name: 'Kwame Boateng',   cls: 'SSS 1', guardian: 'Akua Boateng',   att: 92, fee: 180, status: 'Partial', method: 'Bank' },
  { name: 'Naa Adjoa',       cls: 'JSS 3', guardian: 'Yaw Adjoa',      att: 95, fee: 320, status: 'Paid',    method: 'Card' },
  { name: 'Chinedu Okafor',  cls: 'SSS 2', guardian: 'Ngozi Okafor',   att: 89, fee: 360, status: 'Paid',    method: 'Transfer' },
  { name: 'Aisha Bello',     cls: 'JSS 1', guardian: 'Ibrahim Bello',  att: 99, fee: 280, status: 'Paid',    method: 'Card' },
  { name: 'Tunde Adebayo',   cls: 'SSS 3', guardian: 'Funke Adebayo',  att: 87, fee: 400, status: 'Unpaid',  method: '—' },
  { name: 'Zainab Sule',     cls: 'JSS 2', guardian: 'Hadiza Sule',    att: 96, fee: 320, status: 'Paid',    method: 'Card' },
  { name: 'Emeka Eze',       cls: 'SSS 1', guardian: 'Ifeoma Eze',     att: 91, fee: 360, status: 'Partial', method: 'Bank' },
  { name: 'Ifunanya Obi',    cls: 'JSS 3', guardian: 'Chioma Obi',     att: 94, fee: 320, status: 'Paid',    method: 'Card' },
  { name: 'Olamide Akin',    cls: 'JSS 1', guardian: 'Bola Akin',      att: 97, fee: 280, status: 'Paid',    method: 'Transfer' },
  { name: 'David Owusu',     cls: 'SSS 2', guardian: 'Esi Owusu',      att: 90, fee: 360, status: 'Unpaid',  method: '—' },
  { name: 'Fatima Yusuf',    cls: 'JSS 2', guardian: 'Aminu Yusuf',    att: 99, fee: 320, status: 'Paid',    method: 'Card' },
];

const teachers = [
  { name: 'Mrs. Adaeze Nwosu', subject: 'Mathematics',  classes: 'JSS 1–3', exp: '8 yrs',  color: 'brandBlue',   initials: 'AN' },
  { name: 'Mr. Samuel Kojo',   subject: 'English Lang.', classes: 'SSS 1–3', exp: '12 yrs', color: 'brandPurple', initials: 'SK' },
  { name: 'Ms. Halima Ibrahim',subject: 'Biology',       classes: 'SSS 1–3', exp: '6 yrs',  color: 'brandGreen',  initials: 'HI' },
  { name: 'Mr. Tunde Olawale', subject: 'Physics',       classes: 'SSS 2–3', exp: '10 yrs', color: 'brandBlue',   initials: 'TO' },
  { name: 'Mrs. Ngozi Eze',    subject: 'Chemistry',     classes: 'SSS 1–3', exp: '9 yrs',  color: 'brandPurple', initials: 'NE' },
  { name: 'Mr. Femi Adekunle', subject: 'History',       classes: 'JSS 1–3', exp: '5 yrs',  color: 'brandGreen',  initials: 'FA' },
];

const subjects = [
  { name: 'Mathematics',   score: 78, color: '#60a5fa' },
  { name: 'English Lang.', score: 84, color: '#a78bfa' },
  { name: 'Biology',       score: 81, color: '#4ade80' },
  { name: 'Physics',       score: 72, color: '#60a5fa' },
  { name: 'Chemistry',     score: 76, color: '#a78bfa' },
  { name: 'History',       score: 88, color: '#4ade80' },
];

const topPerformers = [
  { name: 'Aisha Bello',   cls: 'JSS 1', avg: 94, color: 'brandGreen', initials: 'AB' },
  { name: 'Chinedu Okafor', cls: 'SSS 2', avg: 92, color: 'brandBlue',  initials: 'CO' },
  { name: 'Naa Adjoa',     cls: 'JSS 3', avg: 91, color: 'brandPurple',initials: 'NA' },
  { name: 'Fatima Yusuf',  cls: 'JSS 2', avg: 90, color: 'brandGreen', initials: 'FY' },
];

const attendance7d = [
  { day: 'Mon', val: 94 }, { day: 'Tue', val: 96 }, { day: 'Wed', val: 93 },
  { day: 'Thu', val: 97 }, { day: 'Fri', val: 98 }, { day: 'Sat', val: 91 }, { day: 'Sun', val: 96 },
];

const reportFiles = [
  { type: 'PDF', color: 'brandBlue',   title: 'Term 2 Mid-term Results',   meta: 'Auto-emailed to 1,284 parents · 3 days ago' },
  { type: 'CSV', color: 'brandGreen',  title: 'Attendance Summary — Week 6', meta: 'Generated by John Paulson · 1 week ago' },
  { type: 'PDF', color: 'brandPurple', title: 'Fee Collection — Term 2',     meta: 'Generated 2 weeks ago' },
];

const ROLES = {
  admin:   { label: 'Administrator', name: 'John Paulson',  initials: 'JP' },
  teacher: { label: 'Teacher',       name: 'Mrs. Adaeze N.', initials: 'AN' },
  parent:  { label: 'Parent',        name: 'Kofi Mensah',   initials: 'KM' },
};

// ════════════════════════════ STATE ════════════════════════════
let students = JSON.parse(JSON.stringify(seedStudents));
let attendanceState = {}; // { 'JSS 3-2026-05-07': { 'Naa Adjoa': 'present' } }
let currentRole = 'admin';

// ════════════════════════════ HELPERS ════════════════════════════
const $  = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];

const initials = (name) => name.split(' ').map(n => n[0]).slice(0,2).join('').toUpperCase();
const colorFor = (name) => {
  const palette = ['#4ade80', '#60a5fa', '#a78bfa', '#fbbf24', '#f472b6'];
  let h = 0; for (const c of name) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return palette[h % palette.length];
};
const pillClass = (s) => s === 'Paid' ? 'pill--paid' : s === 'Partial' ? 'pill--partial' : 'pill--unpaid';
const fmt$ = (n) => '$' + n.toLocaleString();

const toast = (msg, color = 'brandGreen') => {
  $('#toastMsg').textContent = msg;
  $('#toastDot').className = `w-2 h-2 rounded-full bg-${color}`;
  const t = $('#toast');
  t.classList.add('show');
  clearTimeout(toast._t);
  toast._t = setTimeout(() => t.classList.remove('show'), 2400);
};

// ════════════════════════════ LOGIN ════════════════════════════
$$('#rolePicker .role-pill').forEach(b => {
  b.addEventListener('click', () => {
    $$('#rolePicker .role-pill').forEach(x => x.classList.remove('is-active'));
    b.classList.add('is-active');
    currentRole = b.dataset.role;
  });
});

$('#loginForm').addEventListener('submit', (e) => {
  e.preventDefault();
  const overlay = $('#login');
  overlay.style.transition = 'opacity 0.4s';
  overlay.style.opacity = '0';
  setTimeout(() => {
    overlay.style.display = 'none';
    applyRole(currentRole);
    toast(`Signed in as ${ROLES[currentRole].label}`);
  }, 400);
});

$('#signOutBtn').addEventListener('click', () => {
  const overlay = $('#login');
  overlay.style.display = 'flex';
  overlay.style.opacity = '1';
});

$('#resetDemo').addEventListener('click', () => {
  students = JSON.parse(JSON.stringify(seedStudents));
  attendanceState = {};
  renderAll();
  toast('Demo reset to default state');
});

// ════════════════════════════ ROLE-BASED ACCESS ════════════════════════════
function applyRole(role) {
  currentRole = role;
  const r = ROLES[role];

  // user pill
  $('#userName').textContent = r.name;
  $('#userRoleLbl').textContent = r.label;
  $('#userAvatar').textContent = r.initials;
  $('#welcomeText').textContent = `Welcome back, ${r.name.split(' ')[0]}`;

  // role badge
  $('#roleBadge').innerHTML = `
    <span class="w-1.5 h-1.5 rounded-full bg-brandGreen"></span>
    <span class="text-gray-400">Viewing as</span>
    <span class="text-white font-semibold">${r.label}</span>
  `;

  // sidebar permissions
  let firstAllowed = null;
  $$('.nav-link').forEach(btn => {
    const allowed = (btn.dataset.roles || '').split(',').includes(role);
    btn.classList.toggle('is-disabled', !allowed);
    if (allowed && !firstAllowed) firstAllowed = btn.dataset.tab;
  });

  showTab(firstAllowed || 'dashboard');
}

// ════════════════════════════ TABS ════════════════════════════
function showTab(name) {
  $$('.view').forEach(v => v.classList.toggle('hidden', v.dataset.view !== name));
  $$('.nav-link').forEach(b => b.classList.toggle('is-active', b.dataset.tab === name));
  window.scrollTo({ top: 0, behavior: 'smooth' });
  if (name === 'dashboard')  drawAttendanceChart();
  if (name === 'reports')    drawSubjectBars();
  if (name === 'attendance') initAttendance();
}

document.addEventListener('click', (e) => {
  const t = e.target.closest('[data-tab]');
  if (t && !t.classList.contains('is-disabled')) showTab(t.dataset.tab);
});

// ════════════════════════════ KPI RECALC ════════════════════════════
function recalcKPIs() {
  const expected = students.reduce((s, x) => s + x.fee, 0) + 30000; // padding to keep $54k feel
  const collected = students.reduce((s, x) => {
    if (x.status === 'Paid')    return s + x.fee;
    if (x.status === 'Partial') return s + Math.round(x.fee / 2);
    return s;
  }, 0) + 44000;
  const outstanding = expected - collected;
  const rate = Math.round((collected / expected) * 100);

  $('[data-kpi="students"]').textContent = students.length.toLocaleString();
  $('[data-kpi="feesPaid"]').textContent = '$' + Math.round(collected/1000) + 'k';
  $('[data-kpi="feeCollected"]').textContent = fmt$(collected);
  $('[data-kpi="feeOutstanding"]').textContent = fmt$(outstanding);
  $('[data-kpi="feeRate"]').textContent = rate + '%';
  $('#collectionBar').style.width = rate + '%';
  $('#collectionLbl').textContent = `${fmt$(collected)} of ${fmt$(expected)}`;
  $('#collectionPctLbl').textContent = rate + '% collected';
}

// ════════════════════════════ ATTENDANCE CHART ════════════════════════════
function drawAttendanceChart() {
  const host = $('#attendanceChart');
  if (!host) return;
  const w = host.clientWidth || 600;
  const h = 260;
  const pad = { l: 36, r: 16, t: 18, b: 28 };
  const innerW = w - pad.l - pad.r;
  const innerH = h - pad.t - pad.b;
  const min = 85, max = 100;
  const xs = attendance7d.map((_, i) => pad.l + (i * innerW) / (attendance7d.length - 1));
  const ys = attendance7d.map(d => pad.t + innerH - ((d.val - min) / (max - min)) * innerH);
  const linePath = xs.map((x, i) => `${i === 0 ? 'M' : 'L'}${x},${ys[i]}`).join(' ');
  const areaPath = `${linePath} L${xs[xs.length-1]},${pad.t + innerH} L${xs[0]},${pad.t + innerH} Z`;
  const grid = [0,1,2,3,4].map(i => {
    const y = pad.t + (innerH * i) / 4;
    const v = Math.round(max - ((max - min) * i) / 4);
    return `<line x1="${pad.l}" y1="${y}" x2="${w-pad.r}" y2="${y}" stroke="rgba(255,255,255,0.04)"/>
            <text x="${pad.l - 8}" y="${y + 4}" text-anchor="end" fill="#4b5563" font-size="10">${v}%</text>`;
  }).join('');
  const xLabels = attendance7d.map((d, i) =>
    `<text x="${xs[i]}" y="${h - 8}" text-anchor="middle" fill="#6b7280" font-size="10">${d.day}</text>`
  ).join('');
  const dots = xs.map((x, i) =>
    `<circle class="chart-dot" cx="${x}" cy="${ys[i]}" r="3.5" fill="#0a0a0f" stroke="#60a5fa" stroke-width="2" style="animation-delay:${0.8 + i*0.08}s"/>`
  ).join('');
  host.innerHTML = `
    <svg viewBox="0 0 ${w} ${h}" width="100%" height="100%" preserveAspectRatio="none">
      <defs>
        <linearGradient id="areaG" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#60a5fa" stop-opacity="0.35"/>
          <stop offset="100%" stop-color="#60a5fa" stop-opacity="0"/>
        </linearGradient>
      </defs>
      ${grid}${xLabels}
      <path class="chart-area" d="${areaPath}" fill="url(#areaG)"/>
      <path class="chart-line" d="${linePath}" fill="none" stroke="#60a5fa" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      ${dots}
    </svg>
  `;
}

// ════════════════════════════ DASHBOARD: RECENT FEES ════════════════════════════
function renderRecentFees() {
  $('#recentFees').innerHTML = students.slice(0, 5).map(s => `
    <div class="grid grid-cols-[1.5fr_1fr_1fr_1fr_1fr] items-center px-6 py-3 hover:bg-white/[0.02] transition text-sm">
      <div class="flex items-center gap-3 min-w-0">
        <span class="avatar" style="background:${colorFor(s.name)}">${initials(s.name)}</span>
        <span class="text-white truncate">${s.name}</span>
      </div>
      <div class="text-gray-400">${s.cls}</div>
      <div><span class="pill ${pillClass(s.status)}">${s.status}</span></div>
      <div class="text-gray-400">${s.method}</div>
      <div class="text-right text-gray-200 font-medium">${fmt$(s.fee)}</div>
    </div>
  `).join('');
}

// ════════════════════════════ STUDENTS ════════════════════════════
function renderStudents() {
  if (!$('#studentSearch')) return;
  const q   = $('#studentSearch').value.toLowerCase().trim();
  const cls = $('#studentClass').value;
  const st  = $('#studentStatus').value;

  // Parent role: only their own child
  const visible = currentRole === 'parent'
    ? students.filter(s => s.guardian === ROLES.parent.name)
    : students;

  const filtered = visible.filter(s =>
    (!q || s.name.toLowerCase().includes(q)) &&
    (!cls || s.cls === cls) &&
    (!st  || s.status === st)
  );

  if (!filtered.length) {
    $('#studentRows').innerHTML = `<div class="px-6 py-12 text-center text-gray-500 text-sm">No students match those filters.</div>`;
    return;
  }
  $('#studentRows').innerHTML = filtered.map(s => `
    <div class="grid grid-cols-[2fr_1fr_1fr_1fr_1fr_60px] items-center px-6 py-3 hover:bg-white/[0.02] transition text-sm">
      <div class="flex items-center gap-3 min-w-0">
        <span class="avatar" style="background:${colorFor(s.name)}">${initials(s.name)}</span>
        <div class="min-w-0">
          <div class="text-white truncate">${s.name}</div>
          <div class="text-xs text-gray-500 truncate">${s.guardian}</div>
        </div>
      </div>
      <div class="text-gray-400">${s.cls}</div>
      <div class="text-gray-400 truncate">${s.guardian}</div>
      <div class="text-gray-300">${s.att}%</div>
      <div><span class="pill ${pillClass(s.status)}">${s.status}</span></div>
      <div class="text-right"><button class="text-gray-500 hover:text-white">⋯</button></div>
    </div>
  `).join('');

  $('#studentSubtitle').textContent = `${students.length.toLocaleString()} active · showing ${filtered.length}`;
}

// ════════════════════════════ TEACHERS ════════════════════════════
function renderTeachers() {
  $('#teacherGrid').innerHTML = teachers.map(t => `
    <div class="panel p-5 hover:border-white/10 transition">
      <div class="flex items-center gap-3 mb-4">
        <div class="w-12 h-12 rounded-xl bg-${t.color}/20 text-${t.color} flex items-center justify-center font-display font-bold">${t.initials}</div>
        <div class="min-w-0">
          <div class="text-white font-semibold truncate">${t.name}</div>
          <div class="text-xs text-gray-500">${t.subject}</div>
        </div>
      </div>
      <div class="grid grid-cols-2 gap-3 text-xs pt-3 border-t border-white/5">
        <div><div class="text-gray-500 mb-0.5">Classes</div><div class="text-gray-200">${t.classes}</div></div>
        <div><div class="text-gray-500 mb-0.5">Experience</div><div class="text-gray-200">${t.exp}</div></div>
      </div>
    </div>
  `).join('');
}

// ════════════════════════════ FEES ════════════════════════════
function renderFees() {
  // Parent: only their child's fees
  const visible = currentRole === 'parent'
    ? students.filter(s => s.guardian === ROLES.parent.name)
    : students;

  $('#feeRows').innerHTML = visible.map((s, idx) => {
    const realIdx = students.indexOf(s);
    const action = s.status === 'Paid'
      ? `<span class="text-xs text-gray-500">Paid in full</span>`
      : `<button data-pay="${realIdx}" class="text-xs px-3 py-1.5 rounded-md bg-brandGreen text-ink font-semibold hover:brightness-110">Pay now</button>`;
    return `
      <div class="grid grid-cols-[2fr_1fr_1fr_1fr_1fr_120px] items-center px-6 py-3 hover:bg-white/[0.02] transition text-sm">
        <div class="flex items-center gap-3 min-w-0">
          <span class="avatar" style="background:${colorFor(s.name)}">${initials(s.name)}</span>
          <span class="text-white truncate">${s.name}</span>
        </div>
        <div class="text-gray-400">${s.cls}</div>
        <div><span class="pill ${pillClass(s.status)}">${s.status}</span></div>
        <div class="text-gray-400">${s.method}</div>
        <div class="text-gray-200 font-medium">${fmt$(s.fee)}</div>
        <div class="text-right">${action}</div>
      </div>
    `;
  }).join('');
}

// ════════════════════════════ ATTENDANCE TAB ════════════════════════════
function todayISO() {
  const d = new Date();
  return d.toISOString().slice(0, 10);
}
function attKey(cls, date) { return `${cls}|${date}`; }

function initAttendance() {
  const dateInput = $('#attDate');
  if (!dateInput.value) dateInput.value = todayISO();
  renderAttendance();
}

function renderAttendance() {
  const cls  = $('#attClass').value;
  const date = $('#attDate').value;
  const key  = attKey(cls, date);
  const stateMap = attendanceState[key] || {};

  const list = students.filter(s => s.cls === cls);
  $('#attDateLbl').textContent = `${cls} · ${new Date(date).toDateString()} · ${list.length} students`;

  if (!list.length) {
    $('#attRows').innerHTML = `<div class="panel p-10 text-center text-gray-500 text-sm">No students enrolled in ${cls}.</div>`;
    updateAttCounts();
    return;
  }

  $('#attRows').innerHTML = list.map(s => {
    const status = stateMap[s.name];
    return `
      <div class="att-row">
        <div class="flex items-center gap-3 min-w-0">
          <span class="avatar" style="background:${colorFor(s.name)}">${initials(s.name)}</span>
          <div class="min-w-0">
            <div class="text-white text-sm truncate">${s.name}</div>
            <div class="text-xs text-gray-500 truncate">${s.guardian}</div>
          </div>
        </div>
        <div class="att-toggle" data-student="${s.name}">
          <button class="att-btn ${status==='present'?'is-present':''}" data-status="present">Present</button>
          <button class="att-btn ${status==='late'?'is-late':''}" data-status="late">Late</button>
          <button class="att-btn ${status==='absent'?'is-absent':''}" data-status="absent">Absent</button>
        </div>
      </div>
    `;
  }).join('');

  updateAttCounts();
}

function updateAttCounts() {
  const cls = $('#attClass').value;
  const date = $('#attDate').value;
  const map = attendanceState[attKey(cls, date)] || {};
  let p=0, l=0, a=0;
  Object.values(map).forEach(v => { if (v==='present') p++; else if (v==='late') l++; else if (v==='absent') a++; });
  $('#cntPresent').textContent = p;
  $('#cntLate').textContent = l;
  $('#cntAbsent').textContent = a;
}

document.addEventListener('click', (e) => {
  const btn = e.target.closest('.att-btn');
  if (!btn) return;
  const wrap = btn.parentElement;
  const studentName = wrap.dataset.student;
  const status = btn.dataset.status;
  const cls  = $('#attClass').value;
  const date = $('#attDate').value;
  const key = attKey(cls, date);
  attendanceState[key] = attendanceState[key] || {};
  attendanceState[key][studentName] = status;
  // update buttons in this row
  wrap.querySelectorAll('.att-btn').forEach(b => {
    b.classList.remove('is-present','is-late','is-absent');
    if (b.dataset.status === status) b.classList.add(`is-${status}`);
  });
  updateAttCounts();
});

$('#attClass')?.addEventListener('change', renderAttendance);
$('#attDate')?.addEventListener('change', renderAttendance);

$('#markAllPresent')?.addEventListener('click', () => {
  const cls  = $('#attClass').value;
  const date = $('#attDate').value;
  const key = attKey(cls, date);
  attendanceState[key] = attendanceState[key] || {};
  students.filter(s => s.cls === cls).forEach(s => { attendanceState[key][s.name] = 'present'; });
  renderAttendance();
  toast('All students marked present');
});

$('#saveAttendance')?.addEventListener('click', () => {
  const cls  = $('#attClass').value;
  const date = $('#attDate').value;
  const map = attendanceState[attKey(cls, date)] || {};
  const count = Object.keys(map).length;
  const total = students.filter(s => s.cls === cls).length;
  if (count === 0) { toast('Mark at least one student first', 'brandPurple'); return; }
  toast(`Attendance saved · ${count}/${total} students recorded`);
  // update the dashboard chart number subtly
  const present = Object.values(map).filter(v => v === 'present').length;
  if (total) {
    const pct = Math.round((present / total) * 100);
    $('[data-kpi="attendance"]').textContent = pct + '%';
  }
});

// ════════════════════════════ REPORTS ════════════════════════════
function drawSubjectBars() {
  $('#subjectChart').innerHTML = subjects.map(s => `
    <div class="bar-row">
      <div class="bar-row__label">${s.name}</div>
      <div class="bar-row__track"><div class="bar-row__fill" style="background:${s.color}" data-w="${s.score}"></div></div>
      <div class="bar-row__value">${s.score}</div>
    </div>
  `).join('');
  requestAnimationFrame(() => {
    $$('.bar-row__fill').forEach(el => el.style.width = `${el.dataset.w}%`);
  });
  $('#topPerformers').innerHTML = topPerformers.map((p, i) => `
    <div class="flex items-center gap-3">
      <div class="text-xs text-gray-500 w-4">${i+1}</div>
      <div class="w-8 h-8 rounded-full bg-${p.color}/20 text-${p.color} flex items-center justify-center text-xs font-bold">${p.initials}</div>
      <div class="flex-1 min-w-0"><div class="text-sm text-white truncate">${p.name}</div><div class="text-xs text-gray-500">${p.cls}</div></div>
      <div class="text-sm text-${p.color} font-bold">${p.avg}%</div>
    </div>
  `).join('');
  renderReportList();
}

function renderReportList() {
  $('#reportList').innerHTML = reportFiles.map(r => `
    <div class="flex items-center justify-between p-3 rounded-lg bg-white/[0.03] hover:bg-white/5 transition">
      <div class="flex items-center gap-3">
        <div class="w-8 h-8 rounded-lg bg-${r.color}/15 text-${r.color} flex items-center justify-center text-xs font-bold">${r.type}</div>
        <div>
          <div class="text-white">${r.title}</div>
          <div class="text-xs text-gray-500">${r.meta}</div>
        </div>
      </div>
      <button class="text-xs text-gray-400 hover:text-white">Download</button>
    </div>
  `).join('');
  $('#reportsCount').textContent = `${reportFiles.length} reports · last 30 days`;
}

// ════════════════════════════ ENROLL MODAL ════════════════════════════
function openEnroll()  { $('#modal').classList.add('show'); }
function closeEnroll() { $('#modal').classList.remove('show'); $('#enrollForm').reset(); }

$('#enrollForm').addEventListener('submit', (e) => {
  e.preventDefault();
  const fd = new FormData(e.target);
  students.unshift({
    name: fd.get('name').trim(),
    cls: fd.get('class'),
    guardian: fd.get('guardian').trim(),
    att: 100,
    fee: Number(fd.get('fee')) || 0,
    status: 'Unpaid', method: '—',
  });
  closeEnroll();
  toast(`${students[0].name} enrolled in ${students[0].cls}`);
  renderAll();
});

// ════════════════════════════ PAYMENT MODAL ════════════════════════════
let payIdx = null;
function openPay(idx) {
  payIdx = idx;
  const s = students[idx];
  const due = s.status === 'Partial' ? Math.round(s.fee / 2) : s.fee;
  $('#payStudent').textContent = `${s.name} · ${s.cls}`;
  $('#payAmount').textContent = fmt$(due);
  $('#payBtnAmount').textContent = fmt$(due);
  $('#payBody').classList.remove('hidden');
  $('#payProcessing').classList.add('hidden');
  $('#paySuccess').classList.add('hidden');
  $('#payModal').classList.add('show');
}
function closePay() {
  $('#payModal').classList.remove('show');
  payIdx = null;
}

$('#confirmPay').addEventListener('click', () => {
  $('#payBody').classList.add('hidden');
  $('#payProcessing').classList.remove('hidden');
  setTimeout(() => {
    $('#payProcessing').classList.add('hidden');
    $('#paySuccess').classList.remove('hidden');
    if (payIdx !== null) {
      students[payIdx].status = 'Paid';
      students[payIdx].method = 'Card';
      $('#paySuccessLbl').textContent = `Receipt sent to ${students[payIdx].guardian}.`;
      renderAll();
    }
  }, 1600);
});

document.addEventListener('click', (e) => {
  if (e.target.matches('[data-pay]')) openPay(Number(e.target.dataset.pay));
  if (e.target.closest('[data-close-pay]') || e.target.id === 'payModal') closePay();
  if (e.target.closest('[data-close-modal]') || e.target.id === 'modal') closeEnroll();
});

// ════════════════════════════ INVOICE BLAST ════════════════════════════
function openInvoice() {
  const unpaid = students.filter(s => s.status !== 'Paid');
  const total = unpaid.reduce((sum, s) => sum + (s.status === 'Partial' ? Math.round(s.fee/2) : s.fee), 0);
  $('#invCount').textContent = `${unpaid.length} parents`;
  $('#invTotal').textContent = fmt$(total);
  $('#invoiceBody').classList.remove('hidden');
  $('#invoiceProgress').classList.add('hidden');
  $('#invoiceDone').classList.add('hidden');
  $('#invoiceModal').classList.add('show');
}
function closeInvoice() { $('#invoiceModal').classList.remove('show'); }

$('#confirmInvoice').addEventListener('click', () => {
  $('#invoiceBody').classList.add('hidden');
  $('#invoiceProgress').classList.remove('hidden');
  let p = 0;
  const total = students.filter(s => s.status !== 'Paid').length;
  const tick = setInterval(() => {
    p += Math.random() * 18 + 6;
    if (p >= 100) { p = 100; clearInterval(tick); finish(); }
    $('#invBar').style.width = p + '%';
    const sent = Math.round((p/100) * total);
    $('#invProgressLbl').textContent = `Sending invoice ${sent} of ${total}…`;
  }, 180);
  function finish() {
    setTimeout(() => {
      $('#invoiceProgress').classList.add('hidden');
      $('#invoiceDone').classList.remove('hidden');
      $('#invDoneLbl').textContent = `${total} invoices delivered`;
    }, 250);
  }
});

document.addEventListener('click', (e) => {
  if (e.target.closest('[data-close-invoice]') || e.target.id === 'invoiceModal') closeInvoice();
});

// ════════════════════════════ REPORT GENERATION ════════════════════════════
const REPORT_STEPS = [
  { label: 'Compiling grades from teachers', dur: 1100 },
  { label: 'Calculating GPAs and rankings',  dur: 900  },
  { label: 'Building branded PDF report cards', dur: 1300 },
  { label: 'Emailing 1,284 parents',         dur: 1500 },
];

function openReportGen() {
  $('#reportSteps').innerHTML = REPORT_STEPS.map((s, i) => `
    <div class="report-step" data-step="${i}">
      <div class="report-step__icon" data-icon="${i}">${i+1}</div>
      <div class="text-gray-300">${s.label}</div>
    </div>
  `).join('');
  $('#reportBar').style.width = '0%';
  $('#reportPct').textContent = '0%';
  $('#reportStatus').textContent = 'Preparing…';
  $('#reportDone').classList.add('hidden');
  $('#reportModal').classList.add('show');
  runReportSteps();
}
function closeReportGen() { $('#reportModal').classList.remove('show'); }

function runReportSteps() {
  const total = REPORT_STEPS.reduce((s, x) => s + x.dur, 0);
  let elapsed = 0;
  const startStep = (i) => {
    if (i >= REPORT_STEPS.length) {
      $('#reportBar').style.width = '100%';
      $('#reportPct').textContent = '100%';
      $('#reportStatus').textContent = '✓ All reports delivered';
      // Add a fresh entry to recent reports
      reportFiles.unshift({
        type: 'PDF', color: 'brandPurple',
        title: 'Term 2 Report Cards — All Classes',
        meta: 'Auto-emailed to all guardians · just now',
      });
      renderReportList();
      $('#reportDone').classList.remove('hidden');
      toast('Reports sent to 1,284 parents');
      return;
    }
    const stepEl = $(`.report-step[data-step="${i}"]`);
    const iconEl = $(`.report-step__icon[data-icon="${i}"]`);
    if (i > 0) {
      const prev = $(`.report-step[data-step="${i-1}"]`);
      const prevIcon = $(`.report-step__icon[data-icon="${i-1}"]`);
      prev.classList.remove('is-active');
      prev.classList.add('is-done');
      prevIcon.innerHTML = '✓';
    }
    stepEl.classList.add('is-active');
    iconEl.innerHTML = `<div class="spinner" style="width:14px;height:14px;border-width:2px"></div>`;
    $('#reportStatus').textContent = REPORT_STEPS[i].label + '…';
    // animate bar over duration
    const startElapsed = elapsed;
    const startTime = performance.now();
    const tick = () => {
      const t = performance.now() - startTime;
      const localPct = Math.min(t / REPORT_STEPS[i].dur, 1);
      const cur = startElapsed + localPct * REPORT_STEPS[i].dur;
      const pct = Math.round((cur / total) * 100);
      $('#reportBar').style.width = pct + '%';
      $('#reportPct').textContent = pct + '%';
      if (localPct < 1) requestAnimationFrame(tick);
      else {
        elapsed += REPORT_STEPS[i].dur;
        startStep(i + 1);
      }
    };
    requestAnimationFrame(tick);
  };
  startStep(0);
}

document.addEventListener('click', (e) => {
  if (e.target.closest('[data-close-report]') || e.target.id === 'reportModal') closeReportGen();
});

// ════════════════════════════ QUICK ACTIONS ════════════════════════════
document.addEventListener('click', (e) => {
  const a = e.target.closest('[data-action]');
  if (!a) return;
  const action = a.dataset.action;
  if (action === 'add-student')        openEnroll();
  if (action === 'mark-attendance')    showTab('attendance');
  if (action === 'send-invoices')      openInvoice();
  if (action === 'generate-reports')   openReportGen();
});

// ════════════════════════════ INPUTS ════════════════════════════
['#studentSearch', '#studentClass', '#studentStatus'].forEach(sel => {
  const el = $(sel);
  if (el) el.addEventListener('input', renderStudents);
});

// ════════════════════════════ INIT ════════════════════════════
function renderAll() {
  renderRecentFees();
  renderStudents();
  renderTeachers();
  renderFees();
  renderReportList();
  recalcKPIs();
}

renderAll();
applyRole('admin');

window.addEventListener('resize', () => {
  if (!$('[data-view="dashboard"]').classList.contains('hidden')) drawAttendanceChart();
});
